sudo: required
services:
    - docker

before_install:
    - docker build -t jtrolle/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jtrolle/react-test npm test

after_success:
    - docker build -t jtrolle/multi-client ./client
    - docker build -t jtrolle/multi-server ./server
    - docker build -t jtrolle/multi-nginx ./nginx
    - docker build -t jtrolle/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jtrolle/multi-client
    - docker push jtrolle/multi-server
    - docker push jtrolle/multi-nginx
    - docker push jtrolle/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-3-633344579048
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY